# -*- coding: utf-8 -*-
"""Copy of chaos_vis_241120_polish_2d_quadratics_encrypt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15oxjVzphgcR7FCjC3BwXMJti4_Cmi73t
"""

import datetime

# Creation Date: 2024-11-18
NOTEBOOK_DATE = datetime.datetime.now().strftime("%Y_%m_%d_%H_%M_%S_%f")
OUTPUT_NAME = f"chaos_vis_polish_2d_quadratics_encrypt_{NOTEBOOK_DATE}_output"
OUTPUT_DIR = f"/content/{OUTPUT_NAME}"
PASSWORD = "cha0tic"

FRAMES = 40
CMAPS = ['viridis', 'inferno', 'Greys', 'Purples', 'Blues']

#@title Import Libraries

import numpy as np
import matplotlib.pyplot as plt
from numba import njit
import datetime
import random
import pickle
import shutil
import subprocess
import math
import json
import time
import os

import matplotlib
import matplotlib.cm as cm
import imageio
from tqdm.notebook import tqdm
from concurrent.futures import ProcessPoolExecutor, as_completed

# encrypt hash
import base64
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes
from concurrent.futures import ProcessPoolExecutor

#@title Functions to Check If Attractor is Good

def hash_to_args(hash, password=None):
    if not password:
        password = PASSWORD

    combined = base64.urlsafe_b64decode(hash.encode('utf-8'))
    salt, nonce, tag, ciphertext = combined[:16], combined[16:28], combined[28:44], combined[44:]
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=100000,
        backend=default_backend()
    )
    key = kdf.derive(password.encode())
    cipher = Cipher(algorithms.AES(key), modes.GCM(nonce, tag), backend=default_backend())
    decryptor = cipher.decryptor()
    serialized = decryptor.update(ciphertext) + decryptor.finalize()
    args = pickle.loads(serialized)

    return {
        **{f"a_{i + 1}": args[i] for i in range(6)},
        **{f"b_{i + 1}": args[i + 6] for i in range(6)},
        "x_0": args[-6],
        "y_0": args[-5],
        "x_min": args[-4],
        "y_min": args[-3],
        "x_max": args[-2],
        "y_max": args[-1],
    }

@njit
def compute_trajectory(ax, ay, x0, y0, xmin, xmax, ymin, ymax, max_iter, d0, initial_step, n_points, lyapunov_threshold):
    """
    Computes the trajectory of the attractor and the Lyapunov index.

    Parameters:
    - ax, ay: Coefficients for the equations of motion.
    - x0, y0: Initial conditions for the attractor.
    - xmin, xmax, ymin, ymax: Bounds for the system.
    - max_iter: Maximum number of iterations.
    - d0: Initial distance between trajectories for Lyapunov calculation.
    - initial_step: Perturbed initial step for Lyapunov calculation.
    - n_points: Number of points to retain from the end of the trajectory.
    - lyapunov_threshold: Minimum value of Lyapunov index for success.

    Returns:
    - success: Whether the attractor meets all conditions.
    - lyapunov: The computed Lyapunov index.
    - x_vals_final, y_vals_final: Arrays of the last `n_points` trajectory points.
    """
    # Allocate arrays for storing trajectory values
    x_vals = np.zeros(max_iter, dtype=np.float64)
    y_vals = np.zeros(max_iter, dtype=np.float64)
    x_vals[0], y_vals[0] = x0, y0

    # Initialize Lyapunov index and perturbed trajectory
    lyapunov = 0.0
    xe, ye = initial_step

    # Iterate to compute trajectory and Lyapunov index
    for i in range(1, max_iter):
        # Update primary system equations
        x_vals[i] = (ax[0] + ax[1] * x_vals[i-1] + ax[2] * x_vals[i-1]**2 +
                     ax[3] * x_vals[i-1] * y_vals[i-1] + ax[4] * y_vals[i-1] +
                     ax[5] * y_vals[i-1]**2)
        y_vals[i] = (ay[0] + ay[1] * x_vals[i-1] + ay[2] * x_vals[i-1]**2 +
                     ay[3] * x_vals[i-1] * y_vals[i-1] + ay[4] * y_vals[i-1] +
                     ay[5] * y_vals[i-1]**2)

        # Check bounds
        if x_vals[i] < xmin or x_vals[i] > xmax or y_vals[i] < ymin or y_vals[i] > ymax:
            return False, lyapunov, None, None

        # Check for convergence
        dx = x_vals[i] - x_vals[i-1]
        dy = y_vals[i] - y_vals[i-1]
        if abs(dx) < 1e-10 and abs(dy) < 1e-10:
            return False, lyapunov, None, None

        # Start computing Lyapunov after 2000 iterations
        if i > 2000:
            # Update perturbed system equations
            xenew = (ax[0] + ax[1] * xe + ax[2] * xe**2 + ax[3] * xe * ye +
                     ax[4] * ye + ax[5] * ye**2)
            yenew = (ay[0] + ay[1] * xe + ay[2] * xe**2 + ay[3] * xe * ye +
                     ay[4] * ye + ay[5] * ye**2)

            # Calculate Lyapunov divergence
            dx_lyap = x_vals[i] - xenew
            dy_lyap = y_vals[i] - yenew
            dd = np.sqrt(dx_lyap**2 + dy_lyap**2)
            if dd > 0:
                lyapunov += np.log(abs(dd / d0))
                # Re-normalize perturbed trajectory
                xe = x_vals[i] + d0 * dx_lyap / dd
                ye = y_vals[i] + d0 * dy_lyap / dd

    # Check Lyapunov threshold
    if lyapunov < lyapunov_threshold:
        return False, lyapunov, None, None

    # Return the last `n_points` trajectory values
    return True, lyapunov, x_vals[-n_points:], y_vals[-n_points:]

def test_single_attractor(args, output_dir, max_iter=10**6, debug=False, lyapunov_threshold=5.0, plot_size_threshold=70 * 1024):
    """
    Attempts to generate a random attractor. If it meets certain conditions,
    saves and returns the directory. Otherwise, returns None.

    Parameters:
    - args: Dictionary of parameters for the attractor.
    - output_dir: Directory to save the attractor plot.
    - max_iter: Maximum number of iterations.
    - debug: Whether to print debug messages.
    - lyapunov_threshold: Minimum Lyapunov index required.
    - plot_size_threshold: Minimum plot file size in bytes required.

    Returns:
    - success: True if the attractor meets all conditions, False otherwise.
    """

    def debug_print(s):
        # Print debug messages if debug mode is enabled
        if debug:
            print(s)

    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    # Extract parameters from args
    ax = np.array([args[f'a_{i}'] for i in range(1, 7)], dtype=np.float64)
    ay = np.array([args[f'b_{i}'] for i in range(1, 7)], dtype=np.float64)
    x0, y0 = args['x_0'], args['y_0']
    xmin, ymin = args['x_min'], args['y_min']
    xmax, ymax = args['x_max'], args['y_max']

    # Add border to bounds
    x_border = 0.05 * (xmax - xmin)
    y_border = 0.2 * (ymax - ymin)
    xmin -= x_border
    xmax += x_border
    ymin -= y_border
    ymax += y_border

    # Initialize perturbed trajectory for Lyapunov calculation
    while True:
        xe = x0 + (np.random.rand() - 0.5) / 1000.0
        ye = y0 + (np.random.rand() - 0.5) / 1000.0
        dx = x0 - xe
        dy = y0 - ye
        d0 = np.sqrt(dx**2 + dy**2)
        if d0 > 0:
            break

    # Compute trajectory and Lyapunov index
    n_points = 100000  # Number of points to retain for plotting
    success, lyapunov, x_vals_final, y_vals_final = compute_trajectory(
        ax, ay, x0, y0, xmin, xmax, ymin, ymax, max_iter, d0, np.array([xe, ye]), n_points, lyapunov_threshold
    )

    if not success:
        debug_print("BAD CASE: Condition not met during trajectory computation.")
        return False

    debug_print(f"Lyapunov Index (Chaotic Index) is {lyapunov:.2f} or {(lyapunov / lyapunov_threshold * 100):.2f}% of threshold")
    debug_print(f"Lyapunov Index (Chaotic Index) Threshold is {lyapunov_threshold:.2f}")

    # Generate and save the attractor plot
    fig, ax_plot = plt.subplots(figsize=(5, 5), dpi=100)
    ax_plot.set_xlim(xmin, xmax)
    ax_plot.set_ylim(ymin, ymax)
    ax_plot.scatter(x_vals_final, y_vals_final, s=0.1, color='black')
    ax_plot.axis('off')
    fname_image = os.path.join(output_dir, "plot.png")
    plt.savefig(fname_image, bbox_inches='tight', pad_inches=0)
    plt.close()

    # Check plot size
    plot_size = os.path.getsize(fname_image)
    debug_print(f"Plot Size is {plot_size} bytes or {(plot_size / plot_size_threshold * 100):.2f}% of threshold")
    debug_print(f"Plot Size Threshold is {plot_size_threshold} bytes")

    if plot_size < plot_size_threshold:
        debug_print("BAD CASE: Visually Not Interesting")
        return False

    return True

#@title Functions to Get Density Map for Plotting

@njit
def compute_grid_and_last_position(x0, y0, ax, ay, xmin, xmax, ymin, ymax, x_scale, y_scale, grid, num_iterations):
    """
    Numba-optimized function to compute the density grid and return the last position.

    Args:
        x0, y0: Initial coordinates.
        ax, ay: Coefficients for the attractor equations.
        xmin, xmax, ymin, ymax: Grid boundaries.
        x_scale, y_scale: Precomputed scaling factors.
        grid: The 2D density grid.
        num_iterations: Number of iterations to perform.

    Returns:
        Updated grid and final x, y positions after iterations.
    """
    x, y = x0, y0
    for _ in range(num_iterations):
        # Map to grid indices
        ix = int((x - xmin) * x_scale)
        iy = int((y - ymin) * y_scale)

        # Increment grid cell if within bounds
        if 0 <= ix < grid.shape[1] and 0 <= iy < grid.shape[0]:
            grid[grid.shape[0] - iy - 1, ix] += 1.0

        # Update coordinates using attractor equations
        x_next = (ax[0] + ax[1] * x + ax[2] * x * x +
                  ax[3] * x * y + ax[4] * y + ax[5] * y * y)
        y_next = (ay[0] + ay[1] * x + ay[2] * x * x +
                  ay[3] * x * y + ay[4] * y + ay[5] * y * y)
        x, y = x_next, y_next

    return grid, x, y

def simulate_attractor(args, output_dir, overwrite=False, max_iterations=100_000_000, grid_size=(1920, 1080)):
    """
    Process the attractor density map from a hash, evaluate the attractor path,
    and save the resulting 2D density grid as a pickle file.

    Args:
        args (str): The dictionary containing attractor parameters.
        output_dir (str): Directory to save the output pickle file.
        max_iterations (int): Number of iterations to evaluate the attractor path.
        grid_size (int): Size of the 2D grid for the histogram.
    """
    os.makedirs(output_dir, exist_ok=True)
    log_file = os.path.join(output_dir, f"density_processing_log.txt")
    pickle_file = os.path.join(output_dir, f"density_grid.pkl")
    if not overwrite and os.path.exists(pickle_file):
        print("Pickle file already exists at:", pickle_file)
        return pickle_file

    ax = [args[f'a_{i}'] for i in range(1, 7)]
    ay = [args[f'b_{i}'] for i in range(1, 7)]
    x0, y0, xmin, ymin, xmax, ymax = args['x_0'], args['y_0'], args['x_min'], args['y_min'], args['x_max'], args['y_max']

    x_border = 0.05 * (xmax - xmin)
    y_border = 0.2 * (ymax - ymin)
    xmin -= x_border
    xmax += x_border
    ymin -= y_border * 0.5
    ymax += y_border * 1.5

    x_scale = (grid_size[1] - 1) / (xmax - xmin)
    y_scale = (grid_size[0] - 1) / (ymax - ymin)

    grid = np.zeros(grid_size, dtype=np.float32)
    chunk_size = 10_000_000

    with open(log_file, "w", encoding="utf-8") as log:
        log.write("Processing density grid:\n")
        origin_time = time.time()

        total_chunks = max_iterations // chunk_size
        remaining_iterations = max_iterations % chunk_size

        for chunk in tqdm(range(total_chunks)):
            grid, x0, y0 = compute_grid_and_last_position(
                x0, y0, ax, ay, xmin, xmax, ymin, ymax, x_scale, y_scale, grid, chunk_size
            )
            current_time = time.time()
            elapsed_time = current_time - origin_time
            avg_time = elapsed_time / ((chunk + 1) * chunk_size)
            remaining_time = avg_time * (max_iterations - (chunk + 1) * chunk_size)
            message = (
                f"Iteration {(chunk + 1) * chunk_size}/{max_iterations}\n"
                f"Elapsed Time: {elapsed_time:.2f} seconds\n"
                f"Average Time per Iteration: {avg_time:.6f} seconds\n"
                f"Estimated Time Remaining: {remaining_time:.2f} seconds\n\n"
            )
            log.write(message)

        if remaining_iterations > 0:
            grid, x0, y0 = compute_grid_and_last_position(
                x0, y0, ax, ay, xmin, xmax, ymin, ymax, x_scale, y_scale, grid, remaining_iterations
            )
            current_time = time.time()
            elapsed_time = current_time - origin_time
            avg_time = elapsed_time / max_iterations
            message = (
                f"Iteration {max_iterations}/{max_iterations}\n"
                f"Elapsed Time: {elapsed_time:.2f} seconds\n"
                f"Average Time per Iteration: {avg_time:.6f} seconds\n\n"
            )
            log.write(message)

        with open(pickle_file, 'wb') as f:
            pickle.dump(grid, f)

        final_message = f"Processing complete. Density grid saved to: {pickle_file}\n"
        print(final_message)
        log.write(final_message)

    return pickle_file

def simulate_attractor_and_plot(args, output_dir, cmap, density=15, overwrite=False, max_iterations=100_000_000, grid_size=(1920, 1080)):
    """
    Process the attractor density map from a hash, evaluate the attractor path,
    and save the resulting 2D density grid as a pickle file.

    Args:
        args (str): The dictionary containing attractor parameters.
        output_dir (str): Directory to save the output pickle file.
        max_iterations (int): Number of iterations to evaluate the attractor path.
        grid_size (int): Size of the 2D grid for the histogram.
    """
    os.makedirs(output_dir, exist_ok=True)
    img_file = os.path.join(output_dir, f"frame.png")
    log_file = os.path.join(output_dir, f"density_processing_log.txt")
    pickle_file = os.path.join(output_dir, f"density_grid.pkl")
    if not overwrite and os.path.exists(pickle_file):
        print("Pickle file already exists at:", pickle_file)
        return pickle_file

    ax = [args[f'a_{i}'] for i in range(1, 7)]
    ay = [args[f'b_{i}'] for i in range(1, 7)]
    x0, y0, xmin, ymin, xmax, ymax = args['x_0'], args['y_0'], args['x_min'], args['y_min'], args['x_max'], args['y_max']

    x_border = 0.05 * (xmax - xmin)
    y_border = 0.2 * (ymax - ymin)
    xmin -= x_border
    xmax += x_border
    ymin -= y_border * 1.5
    ymax += y_border * 1.5

    x_scale = (grid_size[1] - 1) / (xmax - xmin)
    y_scale = (grid_size[0] - 1) / (ymax - ymin)

    grid = np.zeros(grid_size, dtype=np.float32)
    chunk_size = 10_000_000

    with open(log_file, "w", encoding="utf-8") as log:
        log.write("Processing density grid:\n")
        origin_time = time.time()

        total_chunks = max_iterations // chunk_size
        remaining_iterations = max_iterations % chunk_size

        for chunk in range(total_chunks):
        # for chunk in tqdm(range(total_chunks)):
            grid, x0, y0 = compute_grid_and_last_position(
                x0, y0, ax, ay, xmin, xmax, ymin, ymax, x_scale, y_scale, grid, chunk_size
            )
            current_time = time.time()
            elapsed_time = current_time - origin_time
            avg_time = elapsed_time / ((chunk + 1) * chunk_size)
            remaining_time = avg_time * (max_iterations - (chunk + 1) * chunk_size)
            message = (
                f"Iteration {(chunk + 1) * chunk_size}/{max_iterations}\n"
                f"Elapsed Time: {elapsed_time:.2f} seconds\n"
                f"Average Time per Iteration: {avg_time:.6f} seconds\n"
                f"Estimated Time Remaining: {remaining_time:.2f} seconds\n\n"
            )
            log.write(message)

        if remaining_iterations > 0:
            grid, x0, y0 = compute_grid_and_last_position(
                x0, y0, ax, ay, xmin, xmax, ymin, ymax, x_scale, y_scale, grid, remaining_iterations
            )
            current_time = time.time()
            elapsed_time = current_time - origin_time
            avg_time = elapsed_time / max_iterations
            message = (
                f"Iteration {max_iterations}/{max_iterations}\n"
                f"Elapsed Time: {elapsed_time:.2f} seconds\n"
                f"Average Time per Iteration: {avg_time:.6f} seconds\n\n"
            )
            log.write(message)

    # Normalize and Apply Log Tranformation to Plot
    grid_min, grid_max = grid.min(), grid.max()
    if grid_max > grid_min:
        grid = (grid - grid_min) / (grid_max - grid_min)

    epsilon = 1e-10  # To avoid division by zero
    for _ in range(density):
        grid = np.log1p(grid + epsilon) / np.log1p(1 + epsilon)

    cmap_func = cm.get_cmap(cmap)
    rgba_image = cmap_func(grid)  # Apply colormap
    rgb_image = np.delete(rgba_image, 3, 2)  # Remove alpha channel
    rgb_image = (rgb_image * 255).astype(np.uint8)  # Convert to uint8
    imageio.imwrite(img_file, rgb_image, format='png')

    return img_file

t = time.time()

hash = """




AQIDBAUGBwgJEBESExQVFgECAwQFBgcICRAREoJ30xEqWck1zeHnGAGme6Q6F-A7bi4zy9sEW0N7nP8HPA-nV2sBP_l27UVxXGyJc7cU8sMVeLuV_7RXBVL_VglIq-0xY0w5_e1GvsusCnCfm9zGXTza8rxgVFyzoUIl8wFajhE79ZXMgpjLGN5axmzntljO6cqz-x6J1IXtxBmSKYH43HvmuwLX8rMko2YdTXrQL84tywyzdtjgiCFWS-KPzc482ylV3sWflEaiHDEau6H3cqfCO-wOgN7oaVmdGcspnitguKJpVTwJKzR2Jjcy0mFICp0XV4iGDmobumNakHcNKTmzHv4KGsVaakwtYZdd5ydwP88w43_4yhWc0jGYnzCmL6IuYdBnNcp0G84O4TnVEAEWK3lu1h3gXh-z3vY8qaFtrbGVUXw4oDrS5Arzx40WK8_Tvh7mMA3Gs56e0gg7iBqOUT4zpH6Zbh6qTIiat0M7CA6MGlE80devUuxLQG0gZbKErjER6sC7lw7T5CdpyNtaxhrp21kzHmgcJ1p0QbcGHXCIuq8yD1TxYVF94rInoMZ9xDGjw7i9MkSyEn5LiAISmThxZHjOABDR9YG7kw6GNYMpbQSoxNR0M1cXF7EnAJXwj-gMyg==


"""

args = hash_to_args(hash.strip())
neg_args = args.copy()

change_arg = "a_4"
all_change_args = ['a_1', 'a_2', 'a_3', 'a_4', 'a_5', 'a_6', 'b_1', 'b_2', 'b_3', 'b_4', 'b_5', 'b_6']
change_offset = 1e-3

cmap = "inferno"
density = 12

err_count = 0

total_frames = 60
attempts_per_frame = 3
frame_lst = [simulate_attractor_and_plot(args, dir, cmap, density, overwrite=True)]

for frame in tqdm(range(1, total_frames+1)):
    dir = os.path.join(OUTPUT_DIR, f"frame_{frame}")

    success = False

    for attempt in range(1, attempts_per_frame+1):
        args[change_arg] += change_offset
        if test_single_attractor(args, dir, debug=False):
            if attempt>1:
                print(f"Step {frame}/{total_frames} SUCCESS at attempt {attempt}")
            else:
                err_count=0
            img = simulate_attractor_and_plot(args, dir, cmap, density, overwrite=True)
            frame_lst.append(img)
            success = True
            break

    if not success:
        err_count += 1
        args[change_arg] -= change_offset*attempts_per_frame

        if err_count <= 4:
            args, neg_args = neg_args, args
            change_offset = -change_offset
            frame_lst = frame_lst[::-1]
            print(f"SWAP SIGN: Step {frame}/{total_frames} FAILED after {attempt} attempts")
        else:
            err_count = 0
            all_change_args.remove(change_arg)
            if all_change_args==[]:
                all_change_args = ['a_1', 'a_2', 'a_3', 'a_4', 'a_5', 'a_6', 'b_1', 'b_2', 'b_3', 'b_4', 'b_5', 'b_6']
            change_arg = random.choice(all_change_args)
            print(f"REDIRECT TO {change_arg}: Step {frame}/{total_frames} FAILED after {attempt} attempts")


frame_lst = frame_lst[::-1]

temp_dir = os.path.join(OUTPUT_DIR, f"{cmap}_temp")
os.makedirs(temp_dir, exist_ok=True)

# Create soft links in the temp directory in the desired order
for i in range(len(frame_lst)-1):
    src = frame_lst[i]
    dst = os.path.join(temp_dir, f"frame_{i:04d}.png")
    os.symlink(src, dst)

output_video = os.path.join(OUTPUT_DIR, f"ALL_{cmap}.mp4")
ffmpeg_command = [
    "ffmpeg", "-y",
    "-framerate", f"{12}",
    "-i", os.path.join(temp_dir, "frame_%04d.png"),
    "-c:v", "libx264",
    "-pix_fmt", "yuv420p",
    output_video
]
try:
    subprocess.run(ffmpeg_command, check=True)
    print(f"Video saved at {output_video}")
except subprocess.CalledProcessError as e:
    print(f"ffmpeg error: {e}")
    print(f"Command: {' '.join(ffmpeg_command)}")
finally:
    # Clean up the temp directory
    shutil.rmtree(temp_dir)

time_used = time.time()-t
print(time_used)
print(time_used/60)

import os
import math
import shutil
import random
import numpy as np
import matplotlib.pyplot as plt
import subprocess
from tqdm import tqdm
from numba import njit

############################################################
# Placeholder encryption and directory helper functions.
# You can replace these with your own implementations if needed.
############################################################

def encrypt_params(params, password):
    # Dummy function, just returns a hash-like string.
    return "fakehash_" + "".join([str(round(p, 4)) for p in params]) + "_end"

def split_hash_into_dirs(encrypted_string, levels=3, segment_len=3):
    # Splits a string like 'abcdef123...' into directories, e.g. 'abc/def/123'
    # Just a placeholder.
    segments = []
    tmp = encrypted_string.replace("fakehash_", "").replace("_end", "")
    while len(tmp) > 0 and len(segments) < levels:
        seg = tmp[:segment_len]
        tmp = tmp[segment_len:]
        segments.append(seg)
    return os.path.join(*segments)

def delete_empty_dirs(path, stop_path):
    # Recursively delete empty directories up to stop_path
    if not os.path.isdir(path):
        return
    if os.path.abspath(path) == os.path.abspath(stop_path):
        return
    if len(os.listdir(path)) == 0:
        os.rmdir(path)
        delete_empty_dirs(os.path.dirname(path), stop_path)

def generate_image_prompt(fname_image, output_dir):
    # Placeholder for additional logic or checks on the image
    # Return True if you accept, or False to trigger cleanup
    return True

############################################################
# The function that saves an attractor once we've found it.
############################################################

def save_attractor(password, a, b, xmin, xmax, ymin, ymax, x_vals, y_vals, base_output_dir):
    """
    Save the attractor with density-based coloring and smoothing in a hash-based directory.
    If the image is smaller than 80KB, deletes all newly created directories up to base_output_dir.
    """
    import matplotlib
    matplotlib.use("Agg")  # So we can save images in headless mode

    # Save the parameters and generate encrypted string
    params = list(a) + list(b) + [x_vals[0], y_vals[0], xmin, ymin, xmax, ymax]
    encrypted_string = encrypt_params(params, password)

    # Create hash-based directory structure
    hash_dir = split_hash_into_dirs(encrypted_string)
    output_dir = os.path.join(base_output_dir, hash_dir)

    # Keep track of the polish directory for cleanup
    polish_dir = os.path.join(base_output_dir)

    # Create the directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    # Save parameters to text file
    fname_params = os.path.join(output_dir, "params.txt")
    with open(fname_params, 'w') as f:
        f.write(encrypted_string + "\n")
        f.write("\n# Attractor parameters and bounds\n")
        f.write(f"xmin: {xmin}\n")
        f.write(f"ymin: {ymin}\n")
        f.write(f"xmax: {xmax}\n")
        f.write(f"ymax: {ymax}\n")

        f.write("\n# Coefficients for the attractor equations\n")
        f.write("# x_next = ax[0] + ax[1]*x + ax[2]*x^2 + ax[3]*x*y + ax[4]*y + ax[5]*y^2\n")
        f.write("# y_next = ay[0] + ay[1]*x + ay[2]*x^2 + ay[3]*x*y + ay[4]*y + ay[5]*y^2\n")
        for i, (ai, bi) in enumerate(zip(a, b)):
            f.write(f"ax[{i}]: {ai}\n")
            f.write(f"ay[{i}]: {bi}\n")

        f.write("\n# Initial conditions\n")
        f.write(f"x0: {x_vals[0]}\n")
        f.write(f"y0: {y_vals[0]}\n")

    # Save the attractor image
    width, height = 500, 500
    fig, ax = plt.subplots(figsize=(5, 5), dpi=100)
    ax.set_xlim(xmin, xmax)
    ax.set_ylim(ymin, ymax)
    ax.scatter(x_vals[100:], y_vals[100:], s=0.1, color='black')
    ax.axis('off')
    fname_image = os.path.join(output_dir, "plot.png")
    plt.savefig(fname_image, bbox_inches='tight', pad_inches=0)
    plt.close()

    # Check image size and delete directories if too small
    try:
        size_bytes = os.path.getsize(fname_image)
    except:
        # If there's some error, treat as "too small"
        return None

    if size_bytes < 70 * 1024:  # 80KB threshold in bytes
        try:
            shutil.rmtree(output_dir)
            delete_empty_dirs(os.path.dirname(output_dir), polish_dir)
            return None
        except Exception as e:
            print(f"Error during cleanup: {e}")
            return None
    else:
        if not generate_image_prompt(fname_image, output_dir):
            try:
                shutil.rmtree(output_dir)
                delete_empty_dirs(os.path.dirname(output_dir), polish_dir)
                return None
            except Exception as e:
                print(f"Error during cleanup: {e}")
                return None

    return output_dir

############################################################
# The function that attempts to generate and validate a single attractor.
############################################################

def process_single_attractor(password, output_dir, max_iter=10**5):
    """
    Attempts to generate a random attractor. If it meets certain conditions,
    saves and returns the directory. Otherwise returns None.
    """

    # Generate random attractor parameters
    np.random.seed(int(random.random() * 1e6))
    ax = 4 * (np.random.rand(6) - 0.5)
    ay = 4 * (np.random.rand(6) - 0.5)
    xmin, xmax = 1e32, -1e32
    ymin, ymax = 1e32, -1e32
    x0, y0 = np.random.rand() - 0.5, np.random.rand() - 0.5

    lyapunov = 0

    # Initialize trajectory
    x_vals = np.zeros(max_iter)
    y_vals = np.zeros(max_iter)
    x_vals[0], y_vals[0] = x0, y0

    # For lyapunov
    while True:
        xe = x_vals[0] + (np.random.rand() - 0.5) / 1000.0
        ye = y_vals[0] + (np.random.rand() - 0.5) / 1000.0
        dx, dy = x_vals[0] - xe, y_vals[0] - ye
        d0 = np.sqrt(dx**2 + dy**2)
        if d0 > 0:
            break

    drawit = True

    for i in range(1, max_iter):
        # Update primary system
        x_vals[i] = (ax[0] + ax[1]*x_vals[i-1] + ax[2]*x_vals[i-1]**2 +
                     ax[3]*x_vals[i-1]*y_vals[i-1] + ax[4]*y_vals[i-1] +
                     ax[5]*y_vals[i-1]**2)
        y_vals[i] = (ay[0] + ay[1]*x_vals[i-1] + ay[2]*x_vals[i-1]**2 +
                     ay[3]*x_vals[i-1]*y_vals[i-1] + ay[4]*y_vals[i-1] +
                     ay[5]*y_vals[i-1]**2)

        # For lyapunov
        xenew = (ax[0] + ax[1]*xe + ax[2]*xe**2 + ax[3]*xe*ye + ax[4]*ye +
                 ax[5]*ye**2)
        yenew = (ay[0] + ay[1]*xe + ay[2]*xe**2 + ay[3]*xe*ye + ay[4]*ye +
                 ay[5]*ye**2)

        # Track min/max
        xmin = min(xmin, x_vals[i])
        ymin = min(ymin, y_vals[i])
        xmax = max(xmax, x_vals[i])
        ymax = max(ymax, y_vals[i])

        # If unbounded, discard
        if xmin < -1e10 or ymin < -1e10 or xmax > 1e10 or ymax > 1e10:
            drawit = False
            break

        dx, dy = x_vals[i] - x_vals[i-1], y_vals[i] - y_vals[i-1]
        if abs(dx) < 1e-10 and abs(dy) < 1e-10:
            drawit = False
            break

        # Start computing lyapunov after 2000 steps
        if i > 2000:
            dx, dy = x_vals[i] - xenew, y_vals[i] - yenew
            dd = np.sqrt(dx**2 + dy**2)
            if dd > 0:
                lyapunov += np.log(abs(dd / d0))
            xe, ye = x_vals[i] + d0 * dx / (dd if dd != 0 else 1e-15), y_vals[i] + d0 * dy / (dd if dd != 0 else 1e-15)

    # Some conditions for "interesting" attractors
    if drawit:
        # If lyapunov is near zero or negative, skip
        if abs(lyapunov) < 10:
            drawit = False
        elif lyapunov < 0:
            drawit = False

    if drawit:
        return save_attractor(password, ax, ay, xmin, xmax, ymin, ymax, x_vals, y_vals, output_dir)

    return None

############################################################
# Function to iterate the final "good" attractor for 10 million steps.
# We also expand bounding box by 20% to keep it within canvas.
############################################################

@njit
def iterate_attractor(ax, ay, x0, y0, num_iter=10_000_000):
    """
    Given the attractor coefficients ax, ay, initial conditions x0, y0,
    iterate the system for num_iter steps and return arrays of shape (num_iter,).
    """
    x_vals = np.zeros(num_iter, dtype=np.float64)
    y_vals = np.zeros(num_iter, dtype=np.float64)
    x_vals[0], y_vals[0] = x0, y0
    for i in range(1, num_iter):
        x_vals[i] = (ax[0] + ax[1]*x_vals[i-1] + ax[2]*x_vals[i-1]**2 +
                     ax[3]*x_vals[i-1]*y_vals[i-1] + ax[4]*y_vals[i-1] +
                     ax[5]*y_vals[i-1]**2)
        y_vals[i] = (ay[0] + ay[1]*x_vals[i-1] + ay[2]*x_vals[i-1]**2 +
                     ay[3]*x_vals[i-1]*y_vals[i-1] + ay[4]*y_vals[i-1] +
                     ay[5]*y_vals[i-1]**2)
    return x_vals, y_vals

############################################################
# We'll now sample discrete trajectories with updated sizes:
#   chunk 0: 30 points  (was 25)
#   chunk 1: 25 points  (was 20)
#   chunk 2: 20 points  (was 15)
#   chunk 3: 15 points  (was 10)
#   chunk 4: 10 points  (was 5)
# We also add a final point at the center (so effectively the last point is the center).
############################################################

def sample_discrete_trajectories(x_vals, y_vals, center_x, center_y, minX, maxX, minY, maxY):
    """
    We'll create 1 + 9 + 90 + 900 + 9000 = 10,000 trajectories as specified,
    but each is 5 points longer than before.
      chunk 0: 1 trajectory, 30 points
      chunk 1: 9 trajectories, 25 points
      chunk 2: 90 trajectories, 20 points
      chunk 3: 900 trajectories, 15 points
      chunk 4: 9000 trajectories, 10 points
    We'll take the first (n-1) samples from the attractor, and add
    one extra final point at the center.
    """
    num_iter = len(x_vals)
    trajectories = []

    # We'll define how many trajectories and how many points each chunk has:
    # chunk 0 -> 1 trajectory of 30 points
    # chunk 1 -> 9 trajectories of 25 points
    # chunk 2 -> 90 trajectories of 20 points
    # chunk 3 -> 900 trajectories of 15 points
    # chunk 4 -> 9000 trajectories of 10 points
    # in total 10,000 trajectories.

    def generate_random_points(x, y, k):
        # Randomly sample an angle between 0 and 2π
        theta = random.uniform(0, 2 * math.pi)
        # Calculate the new point coordinates
        new_x = x + k * math.cos(theta)
        new_y = y + k * math.sin(theta)
        return new_x, new_y

    # The sample_trajectory function picks (n-1) from the attractor, appends center
    def sample_trajectory(n_points, offset):
        # n_points includes the final center point, so we only gather (n_points - 1) from the attractor
        n_gather = n_points - 1
        pts = np.zeros((n_points, 2), dtype=np.float64)
        step = (num_iter - 1 - offset) // (n_gather - 1) if n_gather > 1 else 1
        idx = offset
        for i in range(n_gather):
            if idx >= num_iter:
                idx = num_iter - 1
            pts[i, 0] = x_vals[idx]
            pts[i, 1] = y_vals[idx]
            idx += step
        # The final point is the center
        x_rand = random.uniform(minX, maxX)
        pts[0, 0], pts[0, 1] = x_rand, minY - 0.1*(maxY-minY)
        pts[1, 0], pts[1, 1] = x_rand, minY + 0.1*(maxY-minY)
        pts[-4, 0], pts[-4, 1] = x_rand, maxY + 0.1*(maxY-minY)
        pts[-3, 0], pts[-3, 1] = random.uniform(minX, maxX), maxY + 0.3*(maxY-minY)
        pts[-2, 0], pts[-2, 1] = random.uniform(minX, maxX), maxY + 1*(maxY-minY)
        pts[-1, 0], pts[-1, 1] = random.uniform(minX, maxX), maxY + 2*(maxY-minY)
        return pts

    offset_counter = 0

    add_ons = 20
    step_size = 3

    # chunk 0
    t_30 = sample_trajectory(step_size*5 + add_ons, offset_counter)
    offset_counter += 100
    trajectories.append(t_30)

    # chunk 1
    for _ in range(9):
        t_25 = sample_trajectory(step_size*4 + add_ons, offset_counter)
        offset_counter += 100
        trajectories.append(t_25)

    # chunk 2
    for _ in range(90):
        t_20 = sample_trajectory(step_size*3 + add_ons, offset_counter)
        offset_counter += 100
        trajectories.append(t_20)

    # chunk 3
    for _ in range(900):
        t_15 = sample_trajectory(step_size*2 + add_ons, offset_counter)
        offset_counter += 100
        trajectories.append(t_15)

    # chunk 4
    for _ in range(1000):
        t_10 = sample_trajectory(step_size + add_ons, offset_counter)
        offset_counter += 100
        trajectories.append(t_10)

    return trajectories

############################################################
# We'll reuse the code from earlier to produce a final 30-second video,
# at 30 fps -> 900 frames total. 5 chunks of 6 seconds each.
############################################################

def get_chunk_index(traj_index):
    """
    0 -> trajectory 0 (30 points)
    1 -> trajectories 1..9 (9 of them, 25 points)
    2 -> trajectories 10..99 (90 of them, 20 points)
    3 -> trajectories 100..999 (900 of them, 15 points)
    4 -> trajectories 1000..9999 (9000 of them, 10 points)
    """
    if traj_index == 0:
        return 0
    elif 1 <= traj_index <= 9:
        return 1
    elif 10 <= traj_index <= 99:
        return 2
    elif 100 <= traj_index <= 999:
        return 3
    else:
        return 4

def compute_bspline(points):
    from scipy.interpolate import splprep, splev
    x = points[:, 0]
    y = points[:, 1]
    # s=0 for no smoothing
    tck, u = splprep([x, y], s=0)
    u_dense = np.linspace(0, 1, 5000)
    x_spline, y_spline = splev(u_dense, tck)
    return x_spline, y_spline

# If you want numba acceleration, comment in/out:
@njit
def set_pixel_and_neighbors(img, px, py, val_center=1.0, val_neighbor=0.6):
    if 0 <= px < img.shape[1] and 0 <= py < img.shape[0]:
        img[py, px] = val_center
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                nx = px + dx
                ny = py + dy
                if 0 <= nx < img.shape[1] and 0 <= ny < img.shape[0]:
                    if not (nx == px and ny == py):
                        if img[ny, nx] < val_neighbor:
                            img[ny, nx] = val_neighbor

@njit
def draw_line(img, px0, py0, px1, py1):
    dx = px1 - px0
    dy = py1 - py0
    steps_line = max(abs(dx), abs(dy)) + 1
    xs = np.round(np.linspace(px0, px1, steps_line)).astype(np.int32)
    ys = np.round(np.linspace(py0, py1, steps_line)).astype(np.int32)
    for x_lin, y_lin in zip(xs, ys):
        set_pixel_and_neighbors(img, x_lin, y_lin)

# def main():
# """
# 1) Keep trying to find a "good" attractor until we succeed.
# 2) Once found, iterate it for 10 million steps.
# 3) Expand bounding box by 20%.
# 4) Sample discrete trajectories (with updated sizes + final center point).
# 5) Create a final 30-second video at 30fps (900 frames) with progressive chunk introduction.
# """
import time

base_output_dir = "./outputs"
password = "placeholder_password"

# 1) Repeatedly try to get a good attractor
attempts = 0
max_attempts = 10**9
good_dir = None
while attempts < max_attempts and good_dir is None:
    attempts += 1
    good_dir = process_single_attractor(password, base_output_dir, max_iter=10**5)
    if good_dir is not None:
        print(f"Found a good attractor in {attempts} tries, saved in: {good_dir}")
        break

if good_dir is None:
    print("Failed to find a good attractor after many attempts. Exiting.")
    assert False

# 2) We now load the parameters from the attractor we just found,
#    re-run it for 10 million steps.
fname_params = os.path.join(good_dir, "params.txt")
with open(fname_params, 'r') as f:
    lines = f.readlines()
# We'll parse ax[], ay[], x0, y0, xmin, xmax, ymin, ymax

ax = [0]*6
ay = [0]*6
x0 = 0
y0 = 0
xmin_ = None
ymin_ = None
xmax_ = None
ymax_ = None
for line in lines:
    line = line.strip()
    if line.startswith("ax["):
        idx = int(line.split("ax[")[1].split("]")[0])
        val = float(line.split(":")[1])
        ax[idx] = val
    elif line.startswith("ay["):
        idx = int(line.split("ay[")[1].split("]")[0])
        val = float(line.split(":")[1])
        ay[idx] = val
    elif line.startswith("x0:"):
        x0 = float(line.split(":")[1])
    elif line.startswith("y0:"):
        y0 = float(line.split(":")[1])
    elif line.startswith("xmin:"):
        xmin_ = float(line.split(":")[1])
    elif line.startswith("ymin:"):
        ymin_ = float(line.split(":")[1])
    elif line.startswith("xmax:"):
        xmax_ = float(line.split(":")[1])
    elif line.startswith("ymax:"):
        ymax_ = float(line.split(":")[1])

ax = np.array(ax, dtype=np.float64)
ay = np.array(ay, dtype=np.float64)

print("Iterating attractor for 10 million points...")
num_big_iter = 10_000_000
x_big, y_big = iterate_attractor(ax, ay, x0, y0, num_big_iter)

# 3) Expand bounding box by 20%
minX = x_big.min()
maxX = x_big.max()
minY = y_big.min()
maxY = y_big.max()
wX = maxX - minX
wY = maxY - minY
minX -= 0.2 * wX
maxX += 0.2 * wX
minY -= 0.2 * wY
maxY += 0.2 * wY

center_x = 0.5 * (minX + maxX)
center_y = 0.5 * (minY + maxY)

# 4) Sample discrete trajectories
print("Sampling discrete trajectories (with final center point)...")
all_trajectories = sample_discrete_trajectories(x_big, y_big, center_x, center_y, minX, maxX, minY, maxY)

# We'll produce a final 30-second (30 fps) video: 900 frames total
total_time_seconds = 5
fps = 24
total_frames = total_time_seconds * fps  # 900
chunk_duration_frames = total_frames // 5  # 180
canvas_size = 2000
canvas = np.zeros((canvas_size, canvas_size), dtype=np.float32)

# Precompute B-splines for each trajectory
print("Precomputing B-splines for each trajectory...")
num_trajectories = len(all_trajectories)
splines = []
for t_i in tqdm(range(num_trajectories), desc="B-spline Setup"):
    traj_pts = all_trajectories[t_i]
    x_spl, y_spl = compute_bspline(traj_pts)
    splines.append((x_spl, y_spl))

# Track previous pixel positions
px_prev = [None] * num_trajectories
py_prev = [None] * num_trajectories

print("Rendering frames...")
for frame in tqdm(range(total_frames), desc="Rendering Video"):
    canvas *= 0.8

    for t_i in range(num_trajectories):
        c = get_chunk_index(t_i)
        chunk_start = c * chunk_duration_frames
        if frame < chunk_start:
            continue

        denom = (total_frames - chunk_start)
        alpha = (frame - chunk_start) / denom if denom > 0 else 1.0
        if alpha < 0:
            alpha = 0
        elif alpha > 1:
            alpha = 1

        if alpha <= 0:
            continue

        # Convert alpha to an index in the B-spline
        x_spl, y_spl = splines[t_i]
        idx_float = alpha * (len(x_spl) - 1)
        idx = int(idx_float)
        cx = x_spl[idx]
        cy = y_spl[idx]
        # Convert from attractor coords to pixel coords
        if (maxX - minX) == 0 or (maxY - minY) == 0:
            continue
        px = int((cx - minX) / (maxX - minX) * (canvas_size - 1))
        py = int((cy - minY) / (maxY - minY) * (canvas_size - 1))

        if px_prev[t_i] is None or py_prev[t_i] is None or alpha == 0:
            set_pixel_and_neighbors(canvas, px, py)
        else:
            draw_line(canvas, px_prev[t_i], py_prev[t_i], px, py)

        px_prev[t_i] = px
        py_prev[t_i] = py

    # save frame
    plt.imsave(f"frame_{frame:04d}.png", canvas, cmap='inferno', vmin=0, vmax=1)

# Finally, assemble into a video file
print("Assembling video with ffmpeg...")
subprocess.run([
    "ffmpeg",
    "-y",
    "-framerate", str(fps),
    "-i", "frame_%04d.png",
    "-pix_fmt", "yuv420p",
    "output_video.mp4"
])

print("Done. The final video is output_video.mp4.")

#@title Save Output

import shutil
shutil.make_archive(OUTPUT_NAME, 'zip', OUTPUT_NAME)

from google.colab import files
files.download(f'{OUTPUT_NAME}.zip')